Dockerfile, go.mod, go.sum
Update from go-1.17 to go-1.18
go mod vendor
go mod tidy
=> update to go-1.18

Dockerfile, Makefile, bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml, config/gatekeeper/rbac.authorization.k8s.io_v1_clusterrole_gatekeeper-manager-role.yaml, config/manager/kustomization.yaml, config/manifests/bases/gatekeeper-operator.clusterserviceversion.yaml, deploy/gatekeeper-operator.yaml, pkg/bindata/bindata.go
=> Explicitly enable CGO and release v0.2.6

deploy/gatekeeper-operator.yaml
=> Update deployment.yaml with v0.2.6

api/v1alpha1/gatekeeper_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml, controllers/gatekeeper_controller.go, controllers/gatekeeper_controller_test.go, test/e2e/gatekeeper_controller_test.go
Ref: https://issues.redhat.com/browse/ACM-7470
=> Add overriding webhook operations

deploy/gatekeeper-operator.yaml
This is required for the release GitHub workflow to work when a new tag is created.
=> Run make release

.github/workflows/olm_tests.yaml, .github/workflows/release.yaml, Makefile
ref: https://issues.redhat.com/browse/ACM-9106
Followup to:
- #45
=> Only run `make release` with tags

.github/workflows/olm_tests.yaml, Makefile
I foolishly tried to use it, assuming it would exist :grimacing:
Followup to:
- #46 
- #45 
ref: https://issues.redhat.com/browse/ACM-9106
=> Add `bundle-index-push` Make target

.github/workflows/fast_forward.yaml
ref: https://issues.redhat.com/browse/ACM-8778
=> Add fast-forward workflow

.github/workflows/fast_forward.yaml, .github/workflows/release.yaml
Followup to:
- #48 
- #49 
- #45
=> Fix fast-forward env reference

.github/workflows/olm_tests.yaml, controllers/gatekeeper_controller.go
Ref: https://issues.redhat.com/browse/ACM-9031
=> Remove TODO comments

.github/workflows/ci_tests.yaml
=> [release-3.14] Remove unused matrix from action

controllers/gatekeeper_controller.go, test/e2e/gatekeeper_controller_test.go
Upgrading the gatekeeper causes cert-issue  due to the fact that the same secret name has been created by the service-ca already
Ref: https://issues.redhat.com/browse/ACM-11413
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
=> Fix secret name for openshift mode

test/e2e/case1_audit_from_cache_test.go, test/e2e/e2e_suite_test.go, test/e2e/gatekeeper_controller_test.go
Adds a debug dump for failing E2E tests; Also adjusts/cleans up some variables
=> Add e2e test debugging

controllers/config_controller.go, controllers/config_helper.go, controllers/config_helper_test.go, gatekeeper.yaml, test/e2e/gatekeeper_controller_test.go
When editing the Gatekeeper CR, the config CR doesn't get updated at all. 
Ref: https://issues.redhat.com/browse/ACM-12323
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
=> Fix gatekeeper config update bug

.github/workflows/ci_tests.yaml, .github/workflows/olm_tests.yaml
Not sure whether this is the issue, but it's worth a shot...
=> Store triggering event for Sonarcloud

api/v1alpha1/gatekeeper_types.go, bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml, config/samples/gatekeeper_with_all_values.yaml, controllers/gatekeeper_controller.go, gatekeeper.yaml, test/e2e/gatekeeper_controller_test.go
Ref: https://issues.redhat.com/browse/ACM-12442
=> Add --log-denies to Gatekeeper operator

build/Dockerfile, build/Dockerfile.rhtap
=> Add `-mod=readonly` for Konflux

Makefile, build/bundle.Dockerfile, bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/gatekeeper-operator.clusterserviceversion.yaml
This is necessary now that we're migrating to Konflux--this was previously handled in CPAAS.
=> Handle bundle annotations manually

api/v1alpha1/gatekeeper_types.go, build/common/Makefile.common.mk, bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml, config/gatekeeper/kustomization.yaml, config/samples/gatekeeper_with_all_values.yaml, controllers/gatekeeper_controller.go, controllers/gatekeeper_controller_test.go, deploy/gatekeeper-operator.yaml, pkg/bindata/bindata.go, test/e2e/gatekeeper_controller_test.go
Ref: https://issues.redhat.com/browse/ACM-16936
=> Set mutation-annotation flag to be enabled by default 3.17

Makefile, build/bundle.Dockerfile, build/bundle.Dockerfile.rhtap, bundle/metadata/annotations.yaml
- Add version update to `bundle` Make target
- Add labels from CPaaS
=> Fix annotations

build/konflux-patch.sh, config/manifests/bases/gatekeeper-operator-product.clusterserviceversion.yaml
Align script with product name realignment
Followup to:
- #164
=> Fix Konflux patch script

.tekton/gatekeeper-operator-3-17-pull-request.yaml, .tekton/gatekeeper-operator-3-17-push.yaml
=> Fix Konflux CEL expression

.tekton/gatekeeper-operator-3-17-pull-request.yaml, .tekton/gatekeeper-operator-3-17-push.yaml, .tekton/gatekeeper-operator-bundle-3-17-pull-request.yaml, .tekton/gatekeeper-operator-bundle-3-17-push.yaml, .tekton/images-mirror-set.yaml, build/konflux-patch.sh
I don't actually know whether this will work, but it was in a PR submitted to the FBC, so we'll see...
Also, looks like we'll have to implement an Integration test for Konflux here. I _definitely_ had the gatekeeper and operator images swapped in the script 😬
=> Add ImageDigestMirrorSet for Konflux

.tekton/gatekeeper-operator-bundle-3-18-pull-request.yaml, .tekton/gatekeeper-operator-bundle-3-18-push.yaml
The Conforma push failed, so this might resolve it.
=> [release-3.18] Fix bundle CEL

docs/releasing.md
The current commands don't work for z-streams.
=> Update releasing docs

.github/renovate.json
- Disable kustomize updates
- Make ignorePaths more specific
=> Update MintMaker config
