stolostron/gatekeeper-operator

- bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
- config/manifests/bases/gatekeeper-operator.clusterserviceversion.yaml
Same contact info as used in https://github.com/open-cluster-management/multicluster-observability-operator/blob/3805a8dcf1f4c6f18a0b98527276d8b6169d570b/config/manifests/bases/multicluster-observability-operator.clusterserviceversion.yaml#L51
Refs:
- https://github.com/open-cluster-management/backlog/issues/13248
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>
> Change maintainer info to Red Hat ACM email

- .github/workflows/ci_tests.yaml
- Makefile
- bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/gatekeeper-operator.yaml
- scripts/kind-with-registry.sh
- test/e2e/gatekeeper_controller_test.go
- Reset manifests after apply
- Remove debug logs from E2E test
- Set the default container for `kubectl logs`
- Update `kind-with-registry.sh` to be reusable
> E2E tweaks

- Makefile
- bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
skipRange on its own will cause the upgrade graph to clear in a catalog. We need a replaces as well.
> Explicitly set replaces in the CSV

- Makefile
- bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
skipRange on its own will cause the upgrade graph to clear in a catalog. We need a replaces as well.
> [Manual Cherry-pick] Explicitly set replaces in the CSV

- Makefile
- bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- deploy/gatekeeper-operator.yaml
Followup (and reverts):
- #42 
(Using the `-*` version metadata would replace the original `vX.Y.Z` image, which was an unintended outcome.)
> Release v3.11.2

- .github/workflows/fast_forward.yaml
> Remove `/` for push in fast-forward workflow

- .github/workflows/fast_forward.yaml
Permissions on fast-forwarding weren't allowing the push to a release branch.
Followup to:
- #48
> Checkout with token for fast-forward

- config/gatekeeper/kustomization.yaml
- controllers/gatekeeper_controller_test.go
- pkg/bindata/bindata.go
- test/e2e/gatekeeper_controller_test.go
- test/e2e/util/util.go
In ROSA/HCP env, the gatekeeper-audit pod failed with OOMKilled. 
This PR increases the memory limit to 1Gi to fix this issue. 
Ref: https://issues.redhat.com/browse/ACM-9757
> Increase memory limit for ROSA/HCP env

- Makefile
- docs/releasing.md
- Modify release instructions since fast-forwarding should be disabled between releases.
> Update release instructions

- Makefile
`stolostron/builder` is multi-arch now.
> Remove arch restriction for `docker-build`

- Makefile
- bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
- config/gatekeeper/apps_v1_deployment_gatekeeper-audit.yaml
- config/gatekeeper/apps_v1_deployment_gatekeeper-controller-manager.yaml
- config/manager/manager.yaml
- deploy/gatekeeper-operator.yaml
- pkg/bindata/bindata.go
Change the image from openpolicyagent to quay.io/gateekeeper For now, our dev is using a gatekeeper image from openpolicyagent/gatekeeper in gatekeeper-operator This should be changed to stolostron
Ref: https://issues.redhat.com/browse/ACM-9099
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
> Change from openpolicyagent to quay.io/gateekeeper

- controllers/gatekeeper_controller.go
- test/e2e/gatekeeper_controller_test.go
Upgrading the gatekeeper causes cert-issue  due to the fact that the same secret name has been created by the service-ca already Ref: https://issues.redhat.com/browse/ACM-11413
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
> 🐛 [Manual cherrypick]Fix secret name for openshift mode

- .github/workflows/ci_tests.yaml
- .github/workflows/olm_tests.yaml
- controllers/config_controller.go
- controllers/config_helper.go
- controllers/config_helper_test.go
- controllers/constraintstatus_controller.go
- controllers/cps_controller_helper.go
- controllers/discovery_storage.go
- controllers/gatekeeper_controller.go
- controllers/gatekeeper_controller_test.go
- main.go
- pkg/platform/platform.go
- test/e2e/gatekeeper_controller_test.go
- test/resources/case1_audit_from_cache/constraint-wrong.yaml
ref: https://issues.redhat.com/browse/ACM-11999
- Removes checks for the `--enable-mutation` flag, which has been deprecated since v3.7 and no longer has any effect if it's provided: https://github.com/open-policy-agent/gatekeeper/commit/c36e3d8fbdebe2b28eda0c554b2801f4bd6c4dd7
- Adds a patch in the OLM workflow to remove any `ErrorPreventedResolution` in the Subscription status caused by the OLM OperatorHubio catalog being unavailable
- Tweak logging messages
- Shuts down the Config reconciler and uses the DynamicClient to prevent it from spamming the logs when Gatekeeper is deleted
- Adds a 30s wait to the Config test since the initial update didn't always get picked up while the controller is starting
- Refactors the E2E tests to have a unified webhook check that accepts an …
> Add tests for deploying with disabled webhooks (and then some)

- controllers/config_helper.go
- controllers/cps_controller_helper.go
Leader election is not needed on the "sub" controllers since they can only start when the main controller is the leader. This should help with the test failures.
> Disable leader election on the "sub" controllers

- Makefile
- PROJECT
- README.md
- build/common/config/.golangci.yml
- bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
- config/manifests/bases/gatekeeper-operator.clusterserviceversion.yaml
- config/olm-install/install-resources.yaml
- controllers/config_controller.go
- controllers/config_helper.go
- controllers/config_helper_test.go
- controllers/constraintstatus_controller.go
- controllers/cps_controller_helper.go
- controllers/gatekeeper_controller.go
- controllers/gatekeeper_controller_test.go
- controllers/merge/merge.go
- controllers/merge/merge_test.go
- docs/upgrading-operator-sdk.md
- go.mod
- main.go
- pkg/util/namespace.go
- pkg/util/util.go
- test/e2e/case1_audit_from_cache_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/gatekeeper_controller_test.go
- test/e2e/options.go
The github.com/gatekeeper/gatekeeper-operator repo is archived. This upstream is now solely in the Stolostron GitHub organization.
> Rename the module to the Stolostron organization

- .tekton/gatekeeper-operator-3-17-pull-request.yaml
- .tekton/gatekeeper-operator-3-17-push.yaml
- .tekton/gatekeeper-operator-bundle-3-17-pull-request.yaml
- .tekton/gatekeeper-operator-bundle-3-17-push.yaml
- Makefile
- build/Dockerfile
- build/Dockerfile.rhtap
- build/bundle.Dockerfile
- build/bundle.Dockerfile.rhtap
- build/konflux-patch.sh
- bundle/metadata/annotations.yaml
- Add Konflux Dockerfile
- Reflow YAML with `yq`
- Add required bundle metadata directly to manifests
> Refactor the bundle build

- .tekton/gatekeeper-operator-3-17-push.yaml
- Makefile
- build/konflux-patch.sh
- Add `containerImage` annotation
- Add operator to `relatedImages`
> Update related images/Configuration nudges

- .github/workflows/olm_tests.yaml
- go.mod
`oc` was removed from the latest Ubuntu release.
> Replace `oc` => `kubectl`

- .tekton/gatekeeper-operator-3-17-pull-request.yaml
- .tekton/gatekeeper-operator-3-17-push.yaml
- .tekton/gatekeeper-operator-bundle-3-17-pull-request.yaml
- .tekton/gatekeeper-operator-bundle-3-17-push.yaml
Konflux will build an image for the operator or bundle's containerfile and that containerfile's
dependencies.
It honestly makes me a bit hesitant to restrict the builds so much since they're so wide open right now, but I think the restriction here ultimately makes sense, but I'd appreciate reviewers' thoughts on it in case I missed something!
And in case you're wondering about the triple asterisk like I was, it's not a typo--it's some weird PipelinesAsCode thing it seems: https://pipelinesascode.com/docs/guide/matchingevents/
ref: https://issues.redhat.com/browse/ACM-15393
> Conditionally build Konflux images

- .github/renovate.json
This enables MintMaker Dockerfile updates for the images in `build/*Dockerfile.rhtap`. It sets `pinDigests` so that, when updating, it specifies the digest next to the tag, like:
```
FROM registry.access.redhat.com/ubi9:latest@sha256:<sha256>
```
It also keeps the bundle up-to-date but without pinning a digest since the bundle only leverages a builder for its CLIs and doesn't pass along any binaries to the resulting image.
> Enable Dockerfile image updates

- .github/workflows/ci_tests.yaml
This permits digests to be pinned in the Konflux files while not requiring it in the regular containerfiles.
> [release-3.19] Handle image SHA
